### PR TITLE
Restructrured html, restructured css, restructured styling

### PR DESCRIPTION
**Pull request by netzgestaltung**
hi, wie besprochen habe ich mir das html vorgenommen und bez semantik/SEO sowie inhaltsstrukturierung durchgeackert.

weiters habe ich mir bez des layouts gedanken gemacht und eine full responsive version gebaut sowie elemente mit neuen icon versehen.

es gibt ein automatische accodion, das auf h3s im inhalt anspringt, es kann noch nach bedarf konfiguriert werden.

es gibt ein on page anchors menü, das auch für mobiltelefone optimiert ist(kann auch weggelassen werden)

seht euch das ganze mal an, ob es zusagt oder was ihr noch ändern wolltet.

lg
tom

### CODE REVIEW

**Comment by sqrt2** [comment]
Hi, I assume you've talked to Thomas at some point, though I can't reach him right now.

The issue is that there's also pull request #28 which is almost mergeable (only minor restyling of the form is required). I like most of your design choices, especially the links to the individual sections at the top, but there are some conflicts with @PublicScam's work, and there are merge conflicts with your PR already.

It'd be great if you could rebase your changes onto #28 once it's merged.

**Comment by netzgestaltung** [comment]
i will try - can you give me a hint where to look?

**Comment by PublicScam** [comment]
Hey Tom,
thanks for contributing, I feel like you did a great job, especially the tab version of the criticism area is neat (the current one takes up too much space)
However, the coloring doesn't seem quite finished to me. (eg. hovering menu, hovering images, progress bar, too colorful in my opinion)
Thomas is in Germany right now as far as I know, I guess we should wait on his opinion.
As you pretty much redesigned the whole page, the idea of offering a second design simultaneously came to my mind. We could add a switch button on top. (I wanted to add that for the english version anyway)
Considering your request comment, I wanted to ask how it comes that you think the current design is not fully responsive or mobile-ready? Maybe I just misconceived that point, because on my phone it works.
Last but not least, did you maybe mix up staatsschutz.at with akvorrat.at? You were writing about SEO which was one of our next concerns on akvorrat.at

**Comment by sqrt2** [comment]
@netzgestaltung, I'm not sure what exactly you mean with where to look, but #28 has been merged and deployed now, so you can just build on top off the master branch.

Since you forked at f0e74c8abf313b6618ed851fc04246f8f8088805, the biggest changes that were made are the improvements to the message slider at the top and the restyling of the sidebar, especially the signature form.

**Comment by netzgestaltung** [comment]
as i talked to thomas the goal was to simplify the whole thing, restructure html code with semantics and SEO in mind and make something fresh - my designs are ment as suggestions - i can revert some of them in a minute... the progress bar is maybe a bit too colorfull ;-)

when you look at the html  - its not very simple to base on something new - i just can transport new contents to the different structure

the message slider looks a bit problematic to me when you think of touch devices, where no hover is possible to slide down the contents

as i also redesigned the sidebar - what to do?

i testet the page before for responsiveness and it had some minor issues, contents(eg akvorrat logo) were missing in small views, and srolling was a bit too long

the sidebar was before the main content area, which leaded to bad readabillity on single column reading (subscribe before knowing something?)

so it did work, but there were a lot points to improve

as a last resort the overall design with bootstrap looked very generic and reused (i saw that very often before...)

**Comment by PublicScam** [comment]
Hello Tom,
I get what you say, I'm just trying to track your development progress while being stunned by the mega commits.
No idea what your deal with Thomas was, we are gonna have to wait on him.
The thing with bootstrap and jquery is, your don't have to worry about browser compatibility yourself, thats all gonna be done for you. The last time I realized it was two days ago when sending an xml parsing script to Thomas which wasn't working for him - for me it was, however. After porting it to jQuery the performance increased and - I assume - it works for him now, too. The structure might look some kind neglected, but actually the current state is pretty much how it's supposed to be. Putting the sign and subscribe forms before the rest of the site was even intended as seen in 9b6169a6ab4860e97e0ca915e0ebd62b56f8ceac (It should be visible to everyone at first)
Furthermore, the hovering on mobile view is achived on most browsers by tapping an element. Simply tap the screen and voilà.
The missing AKVorrat.at Logo was made becoming invisible for xs and sm screens (by someone else) to save some space. AKV is referenced in the footer anyway.
I'm glad you joined us and I'm sure we'll find a suitable solution.

**Comment by netzgestaltung** [comment]
hi PublicScam,

i have no problems with jquery ;-) but bootstrap is leading to unsematic and unstructured html markup - and limiting in style options for CSS. as long as i am in, you will never again have any problems with cross browser layouts (down to IE6 if neccessary).

switching the sidebar to the first position is not a technical problem for me (c/p) 

opting content out always seems a "not the best" solution for the most things in my opinion

sure we have to wait for thomas.

i am glad to work on something important like this, and i am happy to join you all!

**Comment by sqrt2** [comment]
I will leave the framework discussion to you, I'd just like to clarify that IE6 is not a target platform for us: IE6 users cannot view our website because their browser doesn't support any secure TLS ciphersuites.

**Comment by netzgestaltung** [comment]
that is also not my goal - i am very happy to NOT support IE6 ;-) just to clearify

**Pull request closed without merging**
