### PR TITLE
add sidebar content

### PR DESCRIPTION
**Pull request by PublicScam**

### CODE REVIEW

**Comment by sqrt2** [comment]
Thomas recently added the donation button to the sidebar (in 96c20503e20ef38210112b14ed759df901cd99ee), in this version it's gone again. I think you should add it back to the new "Mitwirken" box.

I'm also not sure if pushing the link sharing functions this far down the page is good, they are an effective part of our campaign. Maybe move them directly below the signature box?

**Comment by PublicScam** [comment]
Oh thanks, I didn't want to remove it actually.
I'm just working on the signature box right now, I can move the sharing box up a bit, yeah.

**Comment by PublicScam** [comment]
The donate button is back now and the share box moved up a little bit.
Could you check if the sign form works like that?

**Comment by sqrt2** [comment]
Without all the information from of the hidden <input> elements (and possibly also the "op=Unterzeichnen" string from the submit button) the Drupal webform component throws an error.

There's also currently no visible indication of which form elements are required (the first three) and which aren't.

**Comment by PublicScam** [comment]
Isn't the postal code and the age required as well? If you sign something on parlament.gv.at you need to confirm your age and your postal code...

**Comment by sqrt2** [comment]
The list of signatories of a Parlamentarische Bürgerinitiative needs to be able to be matched against the voter registry (having the right to vote is a requirement for signing), so more information is required, but that's not what our petition is, and we only require the first three form elements.

**Comment by PublicScam** [comment]
Fixed required fields. I need to look into styling these later. I know there exist some classes in bootstrap for that purpose but I don't know how to apply them using the browsers validation yet. We could use a jQuery plugin. However, we should try to do such things natively.
Modals were now added. They get us rid of the long page, but still povide the needed information on request.

**Comment by sqrt2** [comment]
I'm not a fan of the modals in their current state because they hide content if JS is deactivated, and I think we should keep all content accessible in this case. (Having the privacy statement inaccessible for especially privacy-minded users is somewhat ironic. Being able to view it without jumping around on the page when JS is available is nice, though.)

**Comment by PublicScam** [comment]
Well, the everyday normal guy does not have JS disabled. Of course there is a minority, just like myself using NoScript, but disabling JS on staatsschutz.at leads to some more problems.
- No signature progress bar
- No slider
- No counter

Therefore, it should be enough to just put the privacy information in a noscript tag. Again, much important content is inaccessible when disabling JS. Securitywise, PDFs are at least just as vulnerable as JS is with modern browsers.

**Comment by sqrt2** [comment]
I would argue that the content you've listed is not at all essential, whereas the other hidden content (especially the privacy statement) has much larger weight. `<noscript>` tags might work, however the href of the link to the privacy statement also needs to be adapted. NoScript users might be a minority, but they're also the kind of people we want to reach, and we shouldn't break their experience if we don't have to.

**Comment by PublicScam** [comment]
Privacy link fix for NoScript users.

**Comment by sqrt2** [comment]
Hey, have you looked into how to visually indicate which fields are required (without having to submit the form first)? I could merge this and just add the red stars and placeholders that we have now, but it sounded like you had something more specific in mind.

**Comment by PublicScam** [comment]
Well, I actually wanted to use bootstraps classes for that purpose, but I haven't had time to figure out the live checking yet. For now, it would be kind if you just add the red stars and I'm going to fix it later.

**Pull request merged**
